import { requireMember, canViewSensitiveCustomerData } from "@/lib/admin";
import { auditStatusLabel } from "@/lib/admin-display";
import { SubmitButton } from "@/components/SubmitButton";
import { createDiscountCodeAction, createMembershipPlanAction, grantPatientMembershipAction, toggleDiscountCodeAction, toggleMembershipPlanAction } from "./actions";
import { isAdminModuleEnabled } from "@/lib/admin-modules";
import { ModuleDisabled } from "@/components/ModuleDisabled";

export const dynamic = "force-dynamic";

interface PlanRow { id: string; name: string; description: string | null; price: number; credits_total: number; valid_days: number | null; usage_scope: string; service_id: string | null; active: boolean; }
interface ServiceRow { id: string; name: string; }
interface PatientRow { id: string; name: string; phone: string; }
interface CodeRow { id: string; code: string; benefit_type: string; kind: string; value: number; min_amount: number; used_count: number; max_uses: number | null; recipient_name: string | null; recipient_phone: string | null; starts_at: string | null; ends_at: string | null; active: boolean; }
interface MembershipRow { id: string; membership_code: string; status: string; credits_total: number; credits_remaining: number; expires_at: string | null; patients: { name: string; phone: string } | null; membership_plans: { name: string } | null; }

export default async function MembershipsPage() {
  const { supabase, clinicId, role, clinicName } = await requireMember();
  if (!(await isAdminModuleEnabled(supabase, clinicId, "memberships"))) return <ModuleDisabled title="會員與套票" />;
  if (!canViewSensitiveCustomerData(role)) return <p className="card p-6 text-sm text-slate-500">目前角色無法查看顧客套票與聯絡資料。</p>;
  const [{ data: plans, error: plansError }, { data: services, error: servicesError }, { data: patients, error: patientsError }, { data: codes, error: codesError }, { data: memberships, error: membershipsError }] = await Promise.all([
    supabase.from("membership_plans").select("id, name, description, price, credits_total, valid_days, usage_scope, service_id, active").eq("clinic_id", clinicId).order("created_at", { ascending: false }),
    supabase.from("services").select("id, name").eq("clinic_id", clinicId).eq("active", true).order("name"),
    supabase.from("patients").select("id, name, phone").eq("clinic_id", clinicId).eq("active", true).order("name").limit(500),
    supabase.from("discount_codes").select("id, code, benefit_type, kind, value, min_amount, used_count, max_uses, recipient_name, recipient_phone, starts_at, ends_at, active").eq("clinic_id", clinicId).order("created_at", { ascending: false }),
    supabase.from("patient_memberships").select("id, membership_code, status, credits_total, credits_remaining, expires_at, patients(name, phone), membership_plans(name)").eq("clinic_id", clinicId).order("created_at", { ascending: false }).limit(200),
  ]);
  const error = plansError ?? servicesError ?? patientsError ?? codesError ?? membershipsError;
  if (error) throw new Error(error.message);
  const planRows = (plans ?? []) as PlanRow[];
  const serviceRows = (services ?? []) as ServiceRow[];
  const patientRows = (patients ?? []) as PatientRow[];
  const codeRows = (codes ?? []) as CodeRow[];
  const membershipRows = (memberships ?? []) as unknown as MembershipRow[];
  const canEdit = role === "owner" || role === "admin";

  return <div className="space-y-6">
    <div><div className="eyebrow">顧客優惠</div><h1 className="text-2xl font-bold text-slate-900">會員、套票與優惠碼</h1><p className="mt-1 text-sm text-slate-500">品牌：{clinicName}。套票以堂數扣抵預約或報名；優惠碼在報名付款前鎖定額度。</p></div>

    {canEdit && <section className="card space-y-4 p-5"><div><h2 className="font-semibold text-slate-900">建立套票方案</h2><p className="mt-1 text-sm text-slate-500">一堂代表一次預約或一張活動票；可限制適用服務。</p></div><form action={createMembershipPlanAction} className="grid grid-cols-1 gap-3 md:grid-cols-2"><label className="text-sm"><span className="label">方案名稱</span><input name="name" required className="input" /></label><label className="text-sm"><span className="label">價格</span><input name="price" type="number" min="0" defaultValue="0" required className="input" /></label><label className="text-sm"><span className="label">堂數</span><input name="credits_total" type="number" min="1" defaultValue="1" required className="input" /></label><label className="text-sm"><span className="label">有效天數（選填）</span><input name="valid_days" type="number" min="1" className="input" /></label><label className="text-sm"><span className="label">使用範圍</span><select name="usage_scope" className="input"><option value="both">預約與報名</option><option value="appointment">僅預約</option><option value="registration">僅報名</option></select></label><label className="text-sm"><span className="label">適用服務（選填）</span><select name="service_id" className="input"><option value="">所有服務</option>{serviceRows.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></label><label className="text-sm md:col-span-2"><span className="label">說明</span><textarea name="description" rows={2} className="input" /></label><div className="md:col-span-2"><SubmitButton className="btn btn-primary">建立方案</SubmitButton></div></form></section>}

    {canEdit && <section className="card space-y-4 p-5"><div><h2 className="font-semibold text-slate-900">建立優惠碼／禮券</h2><p className="mt-1 text-sm text-slate-500">禮券會固定為單次使用；優惠碼可設定使用上限，核銷與付款失敗釋放共用同一套流程。</p></div><form action={createDiscountCodeAction} className="grid grid-cols-1 gap-3 md:grid-cols-3"><label className="text-sm"><span className="label">用途</span><select name="benefit_type" className="input"><option value="coupon">優惠碼</option><option value="voucher">禮券（單次）</option></select></label><label className="text-sm"><span className="label">代碼</span><input name="code" required className="input uppercase" /></label><label className="text-sm"><span className="label">折扣類型</span><select name="kind" className="input"><option value="percent">百分比</option><option value="fixed">固定金額</option></select></label><label className="text-sm"><span className="label">折扣值</span><input name="value" type="number" min="1" defaultValue="10" required className="input" /></label><label className="text-sm"><span className="label">最低金額</span><input name="min_amount" type="number" min="0" defaultValue="0" className="input" /></label><label className="text-sm"><span className="label">使用上限（優惠碼）</span><input name="max_uses" type="number" min="1" className="input" /></label><label className="text-sm"><span className="label">發放對象姓名（禮券）</span><input name="recipient_name" className="input" /></label><label className="text-sm"><span className="label">發放對象電話（禮券）</span><input name="recipient_phone" className="input" /></label><label className="text-sm"><span className="label">開始時間（選填）</span><input name="starts_at" type="datetime-local" className="input" /></label><label className="text-sm"><span className="label">結束時間（選填）</span><input name="ends_at" type="datetime-local" className="input" /></label><div className="md:col-span-3"><SubmitButton className="btn btn-primary">建立</SubmitButton></div></form></section>}

    <section className="card space-y-4 p-5"><div><h2 className="font-semibold text-slate-900">發放套票給顧客</h2><p className="mt-1 text-sm text-slate-500">系統會產生不可猜測的套票序號，顧客報名或預約時輸入序號並使用相同電話驗證。</p></div><form action={grantPatientMembershipAction} className="grid grid-cols-1 gap-3 md:grid-cols-3"><label className="text-sm"><span className="label">顧客</span><select name="patient_id" required className="input"><option value="">請選擇顧客</option>{patientRows.map((patient) => <option key={patient.id} value={patient.id}>{patient.name} · {patient.phone}</option>)}</select></label><label className="text-sm"><span className="label">套票方案</span><select name="plan_id" required className="input"><option value="">請選擇方案</option>{planRows.filter((plan) => plan.active).map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.credits_total} 堂</option>)}</select></label><label className="text-sm"><span className="label">備註（選填）</span><input name="note" className="input" /></label><div className="md:col-span-3"><SubmitButton className="btn btn-secondary">發放套票</SubmitButton></div></form></section>

    <section className="grid gap-5 lg:grid-cols-2"><div className="card overflow-x-auto p-5"><h2 className="mb-3 font-semibold text-slate-900">套票方案</h2><table className="tbl"><thead><tr><th>方案</th><th>堂數</th><th>適用</th><th>狀態</th><th></th></tr></thead><tbody>{planRows.map((plan) => <tr key={plan.id}><td>{plan.name}<div className="text-xs text-slate-400">NT${plan.price.toLocaleString("zh-TW")}</div></td><td>{plan.credits_total}</td><td>{plan.usage_scope === "both" ? "預約／報名" : plan.usage_scope === "appointment" ? "預約" : "報名"}</td><td>{plan.active ? "啟用" : "停用"}</td><td>{canEdit && <form action={toggleMembershipPlanAction}><input type="hidden" name="id" value={plan.id} /><input type="hidden" name="active" value={String(plan.active)} /><SubmitButton className="btn btn-ghost text-xs">{plan.active ? "停用" : "啟用"}</SubmitButton></form>}</td></tr>)}</tbody></table></div><div className="card overflow-x-auto p-5"><h2 className="mb-3 font-semibold text-slate-900">優惠碼／禮券</h2><table className="tbl"><thead><tr><th>用途</th><th>代碼</th><th>折扣</th><th>使用</th><th>對象</th><th>狀態</th><th></th></tr></thead><tbody>{codeRows.map((code) => <tr key={code.id}><td>{code.benefit_type === "voucher" ? "禮券" : "優惠碼"}</td><td className="font-mono">{code.code}</td><td>{code.kind === "percent" ? `${code.value}%` : `NT$${code.value}`}</td><td>{code.used_count}{code.max_uses ? ` / ${code.max_uses}` : ""}</td><td>{code.recipient_name || code.recipient_phone || "不限對象"}</td><td>{code.active ? "啟用" : "停用"}</td><td>{canEdit && <form action={toggleDiscountCodeAction}><input type="hidden" name="id" value={code.id} /><input type="hidden" name="active" value={String(code.active)} /><SubmitButton className="btn btn-ghost text-xs">{code.active ? "停用" : "啟用"}</SubmitButton></form>}</td></tr>)}</tbody></table></div></section>

    <section className="card overflow-x-auto p-5"><h2 className="mb-3 font-semibold text-slate-900">已發放套票</h2><table className="tbl"><thead><tr><th>顧客</th><th>序號</th><th>方案</th><th>剩餘堂數</th><th>狀態</th><th>到期</th></tr></thead><tbody>{membershipRows.map((membership) => <tr key={membership.id}><td>{membership.patients?.name}<div className="text-xs text-slate-500">{membership.patients?.phone}</div></td><td className="font-mono text-xs">{membership.membership_code}</td><td>{membership.membership_plans?.name ?? "—"}</td><td>{membership.credits_remaining} / {membership.credits_total}</td><td>{auditStatusLabel(membership.status)}</td><td>{membership.expires_at ? new Date(membership.expires_at).toLocaleDateString("zh-TW", { timeZone: "Asia/Taipei" }) : "不限期"}</td></tr>)}</tbody></table>{membershipRows.length === 0 && <p className="text-sm text-slate-400">尚未發放套票。</p>}</section>
  </div>;
}
