"use client";

import { useEffect, useState } from "react";

interface Membership { membership_code: string; status: string; credits_total: number; credits_remaining: number; starts_at: string; expires_at: string | null; membership_plans: { name: string; description: string | null; price: number } | { name: string; description: string | null; price: number }[] | null; }
function one<T>(value: T | T[] | null): T | null { return Array.isArray(value) ? value[0] ?? null : value; }
export default function MembershipPage() {
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [birthday, setBirthday] = useState(""); const [memberships, setMemberships] = useState<Membership[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { const token = window.localStorage.getItem("membership_browser_token"); if (token) void load({ browser_token: token }); }, []);
  async function load(body: Record<string, string>) { setLoading(true); setError(null); try { const response = await fetch("/api/membership/portal", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { ok: boolean; data?: { browser_token: string; memberships: Membership[] }; error?: string }; if (!result.ok || !result.data) throw new Error(result.error ?? "查詢失敗"); window.localStorage.setItem("membership_browser_token", result.data.browser_token); setMemberships(result.data.memberships); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "查詢失敗"); } finally { setLoading(false); } }
  function submit(event: React.FormEvent) { event.preventDefault(); void load({ name, phone, birthday }); }
  return <main className="mx-auto flex min-h-screen max-w-2xl flex-col justify-center gap-6 p-6"><div><p className="eyebrow">Membership</p><h1 className="text-2xl font-bold text-slate-900">會員與套票</h1><p className="mt-2 text-sm leading-6 text-slate-500">查看剩餘堂數、有效期限與已啟用方案；資料只會回傳給通過身分驗證的顧客。</p></div><form onSubmit={submit} className="card grid gap-4 p-5 sm:grid-cols-3"><label className="text-sm"><span className="label">姓名</span><input className="input" value={name} onChange={(e) => setName(e.target.value)} required /></label><label className="text-sm"><span className="label">電話</span><input className="input" value={phone} onChange={(e) => setPhone(e.target.value)} required /></label><label className="text-sm"><span className="label">出生年月日</span><input type="date" className="input" value={birthday} onChange={(e) => setBirthday(e.target.value)} required /></label><button className="btn btn-primary sm:col-span-3" disabled={loading}>{loading ? "查詢中…" : "查詢會員資料"}</button></form>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<section className="space-y-3">{memberships.length === 0 ? <div className="card p-6 text-center text-sm text-slate-400">尚無會員套票資料。</div> : memberships.map((membership) => { const plan = one(membership.membership_plans); return <article key={membership.membership_code} className="card space-y-3 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-900">{plan?.name ?? "會員方案"}</h2><p className="mt-1 font-mono text-xs text-slate-400">{membership.membership_code}</p></div><span className={`badge ${membership.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{membership.status}</span></div><div className="flex items-end justify-between"><div><p className="text-xs text-slate-500">剩餘堂數</p><p className="mt-1 text-2xl font-bold text-slate-950">{membership.credits_remaining}<span className="ml-1 text-sm font-normal text-slate-400">/ {membership.credits_total}</span></p></div><p className="text-right text-xs text-slate-500">{membership.expires_at ? `到期：${new Date(membership.expires_at).toLocaleDateString("zh-TW", { timeZone: "Asia/Taipei" })}` : "不限期"}</p></div></article>; })}</section></main>;
}
