// Database exception text can contain imported values or provider details.
// Only exact errors generated by execute_data_import are shown to operators.
const SAFE_REASONS: Record<string, string> = {
  "row must be an object": "資料列格式不正確",
  "invalid name": "姓名或服務名稱未填，或超過 120 字",
  "invalid phone": "電話格式不正確，請填寫 8 至 20 碼",
  "phone patient limit reached": "此電話對應的顧客數已達品牌上限",
  "service already exists": "服務名稱已存在",
  "patient not found": "找不到相符的顧客姓名與電話",
  "membership plan not found": "找不到有效的套票方案",
  "credits must be positive": "剩餘堂數必須大於零",
};

export interface SafeImportError {
  row: number;
  reason: string;
}

export function safeImportErrors(value: unknown): SafeImportError[] {
  if (!Array.isArray(value)) return [];
  return value.slice(0, 500).map((item): SafeImportError => {
    const row = typeof item === "object" && item !== null && "row" in item ? item.row : 0;
    const reason = typeof item === "object" && item !== null && "reason" in item ? item.reason : "";
    const index = typeof row === "number" && Number.isSafeInteger(row) && row >= 0 && row <= 500 ? row : 0;
    return {
      row: index,
      reason: typeof reason === "string" && Object.hasOwn(SAFE_REASONS, reason)
        ? SAFE_REASONS[reason]
        : index === 0
          ? "匯入工作失敗，請稍後重試或聯絡服務人員"
          : "此列無法匯入，請檢查資料內容或聯絡服務人員",
    };
  });
}
