import Link from "next/link";
import { requireNonProvider } from "@/lib/admin";
import { createSupabaseServer } from "@/lib/supabase-server";
import { SubmitButton } from "@/components/SubmitButton";
import { addPurchaseOrderItemAction, createPurchaseOrderAction, createSupplierAction, finalizeStocktakeAction, receivePurchaseOrderAction, setPurchaseOrderOrderedAction } from "./actions";

export const dynamic="force-dynamic";
function one<T>(value:T|T[]|null):T|null{return Array.isArray(value)?value[0]??null:value;}
function money(value:number):string{return `NT$${Number(value).toLocaleString("zh-TW")}`;}
const STATUS:Record<string,string>={draft:"草稿",ordered:"已下單",received:"已入庫",cancelled:"已取消"};

export default async function SupplyPage({searchParams}:{searchParams:Promise<{order_id?:string}>}){
  const member=await requireNonProvider();const params=await searchParams;const supabase=await createSupabaseServer();
  const [suppliers,items,orders,stocktakes]=await Promise.all([
    supabase.from("inventory_suppliers").select("id,name,contact_name,phone,email,active").eq("clinic_id",member.clinicId).eq("active",true).order("name"),
    supabase.from("inventory_items").select("id,name,sku,unit,stock_on_hand,retail_price").eq("clinic_id",member.clinicId).eq("active",true).order("name"),
    supabase.from("purchase_orders").select("id,order_no,status,expected_at,note,created_at,inventory_suppliers(name),purchase_order_items(id,item_id,quantity,unit_cost,received_quantity,inventory_items(name,unit))").eq("clinic_id",member.clinicId).order("created_at",{ascending:false}).limit(100),
    supabase.from("inventory_stocktakes").select("id,stocktake_no,status,note,completed_at,inventory_stocktake_items(id,system_quantity,actual_quantity,variance,inventory_items(name,unit))").eq("clinic_id",member.clinicId).order("created_at",{ascending:false}).limit(20),
  ]);const error=[suppliers.error,items.error,orders.error,stocktakes.error].find(Boolean);if(error)throw new Error(error.message);
  const selected=(orders.data??[]).find(order=>order.id===params.order_id)??null;
  return <div className="admin-page"><div className="admin-page-header"><div><p className="eyebrow">美業營運</p><h1 className="admin-page-title">採購與盤點</h1><p className="admin-page-description">採購單收貨時一次入庫；盤點完成時保留帳面數量、實際數量與差異。</p></div><Link href="/admin/beauty" className="btn btn-secondary">返回美業營運</Link></div>
  <section className="grid gap-5 xl:grid-cols-2"><form action={createSupplierAction} className="admin-section p-4"><h2 className="font-semibold">新增供應商</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm"><span className="label">供應商名稱</span><input name="name" className="input" required/></label><label className="text-sm"><span className="label">聯絡人</span><input name="contact_name" className="input"/></label><label className="text-sm"><span className="label">電話</span><input name="phone" className="input"/></label><label className="text-sm"><span className="label">Email</span><input name="email" type="email" className="input"/></label><label className="text-sm sm:col-span-2"><span className="label">備註</span><input name="note" className="input"/></label><SubmitButton className="btn btn-primary sm:col-span-2">建立供應商</SubmitButton></div></form>
  <form action={createPurchaseOrderAction} className="admin-section p-4"><h2 className="font-semibold">建立採購單</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm"><span className="label">供應商</span><select name="supplier_id" className="input" required defaultValue=""><option value="" disabled>選擇供應商</option>{(suppliers.data??[]).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className="text-sm"><span className="label">預計到貨日</span><input name="expected_at" type="date" className="input"/></label><label className="text-sm"><span className="label">第一個品項</span><select name="item_id" className="input" required defaultValue=""><option value="" disabled>選擇品項</option>{(items.data??[]).map(row=><option key={row.id} value={row.id}>{row.name} · 庫存 {row.stock_on_hand}{row.unit}</option>)}</select></label><label className="text-sm"><span className="label">數量</span><input name="quantity" type="number" min="0.01" step="0.01" className="input" required/></label><label className="text-sm"><span className="label">單位成本</span><input name="unit_cost" type="number" min="0" className="input" required/></label><label className="text-sm"><span className="label">備註</span><input name="note" className="input"/></label><SubmitButton className="btn btn-primary sm:col-span-2">建立採購單</SubmitButton></div></form></section>
  <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="admin-table-shell"><div className="admin-section-header"><h2 className="font-semibold">採購單</h2></div><table className="tbl"><thead><tr><th>單號</th><th>供應商</th><th>金額</th><th>狀態</th></tr></thead><tbody>{(orders.data??[]).map(order=>{const lines=order.purchase_order_items??[];const total=lines.reduce((sum,line)=>sum+Number(line.quantity)*Number(line.unit_cost),0);return <tr key={order.id}><td><Link href={`/admin/beauty/supply?order_id=${order.id}`} className="font-medium text-brand-700 hover:underline">{order.order_no}</Link><div className="text-xs text-slate-400">{order.expected_at||"未設到貨日"}</div></td><td>{one(order.inventory_suppliers)?.name}</td><td>{money(total)}</td><td><span className="badge bg-slate-100 text-slate-600">{STATUS[order.status]??order.status}</span></td></tr>})}</tbody></table></div>
  <div className="admin-section self-start">{!selected?<p className="p-10 text-center text-sm text-slate-400">選擇採購單查看明細</p>:<><div className="admin-section-header"><div><p className="text-xs text-slate-500">{selected.order_no}</p><h2 className="font-semibold">{one(selected.inventory_suppliers)?.name}</h2></div><span className="badge bg-slate-100">{STATUS[selected.status]}</span></div><div className="space-y-4 p-4"><div className="divide-y divide-slate-100">{(selected.purchase_order_items??[]).map(line=><div key={line.id} className="flex justify-between py-2 text-sm"><span>{one(line.inventory_items)?.name} · {line.quantity}{one(line.inventory_items)?.unit}</span><strong>{money(Number(line.quantity)*Number(line.unit_cost))}</strong></div>)}</div>{selected.status==="draft"&&<form action={addPurchaseOrderItemAction} className="grid gap-2 sm:grid-cols-3"><input type="hidden" name="order_id" value={selected.id}/><select name="item_id" className="input" required defaultValue=""><option value="" disabled>增加品項</option>{(items.data??[]).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><input name="quantity" type="number" min="0.01" step="0.01" placeholder="數量" className="input" required/><input name="unit_cost" type="number" min="0" placeholder="單位成本" className="input" required/><SubmitButton className="btn btn-secondary sm:col-span-3">加入採購單</SubmitButton></form>}<div className="flex gap-2">{selected.status==="draft"&&<form action={setPurchaseOrderOrderedAction}><input type="hidden" name="id" value={selected.id}/><SubmitButton className="btn btn-secondary">標記已下單</SubmitButton></form>}{["draft","ordered"].includes(selected.status)&&<form action={receivePurchaseOrderAction}><input type="hidden" name="id" value={selected.id}/><SubmitButton className="btn btn-primary">全數收貨並入庫</SubmitButton></form>}</div></div></>}</div></section>
  <section className="admin-section p-4"><h2 className="font-semibold">本次盤點</h2><p className="mt-1 text-xs text-slate-500">送出後立即以實際數量更新庫存，並保存每項差異。</p><form action={finalizeStocktakeAction} className="mt-4"><div className="admin-table-shell"><table className="tbl"><thead><tr><th>品項</th><th>帳面數量</th><th>實際數量</th></tr></thead><tbody>{(items.data??[]).map(item=><tr key={item.id}><td>{item.name}<div className="text-xs text-slate-400">{item.sku||"—"}</div></td><td>{item.stock_on_hand} {item.unit}</td><td><input name={`count:${item.id}`} type="number" min="0" step="0.01" defaultValue={item.stock_on_hand} className="input max-w-40" required/></td></tr>)}</tbody></table></div><label className="mt-3 block text-sm"><span className="label">盤點備註</span><input name="note" className="input"/></label><SubmitButton className="btn btn-primary mt-3">完成盤點</SubmitButton></form></section>
  {(stocktakes.data??[]).length>0&&<section className="admin-table-shell"><div className="admin-section-header"><h2 className="font-semibold">最近盤點</h2></div><table className="tbl"><thead><tr><th>盤點單號</th><th>完成時間</th><th>差異</th><th>備註</th></tr></thead><tbody>{(stocktakes.data??[]).map(stocktake=><tr key={stocktake.id}><td>{stocktake.stocktake_no}</td><td>{stocktake.completed_at?new Date(stocktake.completed_at).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"}):"—"}</td><td>{(stocktake.inventory_stocktake_items??[]).filter(line=>Number(line.variance)!==0).map(line=>`${one(line.inventory_items)?.name} ${Number(line.variance)>0?"+":""}${line.variance}`).join("、")||"無差異"}</td><td>{stocktake.note||"—"}</td></tr>)}</tbody></table></section>}
  </div>;
}
