import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
const read=p=>readFileSync(p,'utf8');
async function factory(path,name,deps){const tree=ts.createSourceFile(path,read(path),ts.ScriptTarget.Latest,true,path.endsWith('tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS);const body=tree.statements.filter(n=>!ts.isImportDeclaration(n)).map(n=>n.getText(tree).replace(/^export default /,'').replace(/^export /,'')).join('\n');const {outputText}=ts.transpileModule(`export function factory(deps){const {${deps.join(',')}}=deps;${body};return ${name};}`,{fileName:'x.tsx',compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.React}});return (await import('data:text/javascript;base64,'+Buffer.from(outputText).toString('base64'))).factory;}
const reportRange=(await factory('lib/report-range.ts','reportRange',[]))({});
const errorCategory=(await factory('lib/error-category.ts','errorCategory',[]))({});
const adminErrorMessage=(await factory('lib/admin-query.ts','adminErrorMessage',['errorCategory']))({errorCategory});
const adminQuery=(await factory('lib/admin-query.ts','adminQuery',['errorCategory']))({errorCategory});
const fetchAllSupabasePages=(await factory('lib/supabase-pagination.ts','fetchAllSupabasePages',['adminQuery','adminErrorMessage']))({adminQuery,adminErrorMessage});
const routeFactory=await factory('app/api/admin/reports/route.ts','GET',['reportRange','fetchAllSupabasePages','requireNonProvider','canViewSensitiveCustomerData','fail']);
const pageFactory=await factory('app/admin/reports/page.tsx','ReportsPage',['React','Link','reportRange','fetchAllSupabasePages','requireNonProvider','createServiceClient','formatDateTime','FunnelBarChart','TrendLineChart','auditStatusLabel','registrationStatusLabel']);
const at='2026-01-15T04:00:00.000Z';
function fixture(){return {appointments:['booked','confirmed','done','no_show','cancelled'].map((status,i)=>({id:'a'+i,clinic_id:'own',start_at:at,status,membership_id:null,patients:{name:'=SYNTHETIC',phone:'000'},doctors:{name:'A'},services:{name:'B'}})),registrations:['confirmed','attended','no_show','cancelled','waitlisted','pending','cancelled'].map((status,i)=>({id:'r'+i,registration_no:'r'+i,clinic_id:'own',created_at:at,status,amount:100,discount_amount:i<4?(i+1)*10:0,payment_status:'not_required',membership_id:null})),payment_orders:['paid','paid','failed','expired'].map((status,i)=>({id:'p'+i,merchant_order_no:'p'+i,clinic_id:'own',created_at:at,status,amount:[100,250,300,400][i]})),sales_payments:[{id:'s',clinic_id:'own',received_at:at,amount:120}],crm_delivery_logs:['sent','sent','failed','skipped','pending'].map((status,i)=>({id:'c'+i,clinic_id:'own',created_at:at,status})),funnel_events:[],waitlist_entries:[...['promoted','waiting','cancelled'].map((status,i)=>({id:'w'+i,clinic_id:'own',created_at:at,updated_at:at,status})),{id:'old',clinic_id:'own',created_at:'2026-01-14T15:59:59.000Z',updated_at:at,status:'promoted'}]};}
function client(data,bad){return {from:table=>{const filters=[];let head=false,lo=0,hi=999;const q={select:(_,opts)=>{head=opts?.head;return q;},eq:(k,v)=>{filters.push(r=>r[k]===v);return q;},gte:(k,v)=>{filters.push(r=>r[k]>=v);return q;},lte:(k,v)=>{filters.push(r=>r[k]<=v);return q;},order:()=>q,range:(a,b)=>{lo=a;hi=b;return q;},then:(resolve,reject)=>{const rows=(data[table]??[]).filter(r=>filters.every(f=>f(r)));return Promise.resolve({data:rows.slice(lo,hi+1),count:head?rows.length:null,error:bad?{message:'PRIVATE_SECRET'}:null}).then(resolve,reject);}};return q;}};}
const params={from:'2026-01-15',to:'2026-01-15'};
function setup(data=fixture(),role='admin',bad=false){const db=client(data,bad);const member={supabase:db,clinicId:'own',clinicName:'Synthetic',role};return {route:routeFactory({reportRange,fetchAllSupabasePages,requireNonProvider:async()=>member,canViewSensitiveCustomerData:r=>r==='admin',fail:()=>new Response('安全錯誤',{status:500})}),page:pageFactory({React,Link:({href,children})=>React.createElement('a',{href},children),reportRange,fetchAllSupabasePages,requireNonProvider:async()=>member,createServiceClient:()=>db,formatDateTime:v=>v,FunnelBarChart:()=>null,TrendLineChart:()=>null,auditStatusLabel:v=>v,registrationStatusLabel:v=>v})};}
async function csv(route,query='from=2026-01-15&to=2026-01-15'){return route({nextUrl:new URL('https://example.invalid/?'+query)});}
test('shared range defaults to 30 Taipei days and normalizes reversed dates',()=>{const r=reportRange(null,null,new Date('2026-01-20T16:00:00Z'));assert.equal(r.startDate,'2025-12-23');assert.equal(r.endDate,'2026-01-21');assert.deepEqual(reportRange('2026-01-16','2026-01-15'),reportRange('2026-01-15','2026-01-16'));assert.equal(reportRange('2024-02-29','2024-02-29').start,'2024-02-28T16:00:00.000Z');});
test('invalid calendar date falls back without crashing',()=>{assert.equal(reportRange('2026-02-30','2026-02-30',new Date('2026-03-01T00:00:00Z')).endDate,'2026-03-01');});
test('fixed report cohort reconciles statuses denominators payments CRM and waitlist',async()=>{const html=renderToStaticMarkup(await setup().page({searchParams:Promise.resolve(params)}));for(const text of ['25.0%','33.3%','1 / 4','1 / 3','2 筆 · NT$350','1 筆 · NT$120','NT$100','1 / 1'])assert(html.includes(text),text);assert(!html.includes('66.7%'));});
test('CSV includes 25 rows across all six report domains and escapes spreadsheet formulas',async()=>{const text=await(await csv(setup().route)).text();assert.equal(text.trim().split('\r\n').length,26);for(const kind of ['預約','報名','後台收款','線上付款','CRM 投遞','候補'])assert(text.includes(kind));assert(text.includes("'=SYNTHETIC"));});
test('CSV and UI normalize reversed dates consistently',async()=>{const s=setup();assert.equal(await(await csv(s.route,'from=2026-01-16&to=2026-01-15')).text(),await(await csv(s.route,'from=2026-01-15&to=2026-01-16')).text());});
test('foreign clinic query parameter cannot select foreign rows',async()=>{const data=fixture();data.appointments.push({...data.appointments[0],id:'FOREIGN_MARKER',clinic_id:'foreign'});assert(!(await(await csv(setup(data).route,'from=2026-01-15&to=2026-01-15&clinic_id=foreign')).text()).includes('FOREIGN_MARKER'));});
test('Taipei boundary excludes adjacent days and includes both endpoints',async()=>{const data=fixture();data.appointments=['2026-01-14T15:59:59.999Z','2026-01-14T16:00:00.000Z','2026-01-15T15:59:59.999Z','2026-01-15T16:00:00.000Z'].map((start_at,i)=>({...data.appointments[0],id:'boundary'+i,start_at}));const text=await(await csv(setup(data).route)).text();assert(!text.includes('boundary0'));assert(text.includes('boundary1'));assert(text.includes('boundary2'));assert(!text.includes('boundary3'));});
test('pagination exports beyond 1000 rows without omissions',async()=>{const data=fixture();data.appointments=Array.from({length:1001},(_,i)=>({...data.appointments[0],id:'page'+i}));const text=await(await csv(setup(data).route)).text();assert(text.includes('page1000'));assert.equal(text.trim().split('\r\n').length,1022);});
test('no-PII role and failure paths never expose private fields',async()=>{assert(!(await(await csv(setup(fixture(),'staff').route)).text()).includes('SYNTHETIC'));const result=await csv(setup(fixture(),'admin',true).route);assert.equal(result.status,500);assert(!(await result.text()).includes('PRIVATE_SECRET'));});
test('empty report renders no denominator as dash',async()=>{const html=renderToStaticMarkup(await setup({}).page({searchParams:Promise.resolve(params)}));assert(html.includes('—'));assert(!html.includes('NaN'));});
